-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th7 29, 2019 lúc 05:31 PM
-- Phiên bản máy phục vụ: 10.1.38-MariaDB
-- Phiên bản PHP: 7.3.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `test2`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `products`
--

CREATE TABLE `products` (
  `idp` int(15) NOT NULL,
  `idg_1` int(15) DEFAULT NULL,
  `idg_2` int(15) DEFAULT NULL,
  `product_name` varchar(255) CHARACTER SET utf8 NOT NULL,
  `product_details` varchar(1000) CHARACTER SET utf8 NOT NULL,
  `newprice` int(10) NOT NULL,
  `oldprice` int(10) NOT NULL,
  `qty` int(5) NOT NULL,
  `img` varchar(60) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Đang đổ dữ liệu cho bảng `products`
--

INSERT INTO `products` (`idp`, `idg_1`, `idg_2`, `product_name`, `product_details`, `newprice`, `oldprice`, `qty`, `img`) VALUES
(65, 1, 1, 'iPhone Xs Max 256GBgjkjfaks', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Super AMOLED\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	Super Retina HD\r\nĐộ phân giải màn hình :	1242 x 2688 Pixels\r\nMàn hình :	6.5 inchs\r\nMặt kính màn hình :	Kính Cường Lực\r\nCamera Trước\r\nĐộ phân giải :	7.0 MP\r\nThông tin khác :	Selfie ngược sáng HDR, Camera góc rộng, Nhận diện khuôn mặt\r\nCamera Sau\r\nĐộ phân giải :	Dual Camera 12.0 MP\r\nQuay phim :	4K\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Zoom quang học, Chụp ảnh xóa phông, A.I Camera, HDR, Panorama, Chống rung quang học\r\nCấu hình phần cứng\r\nTốc độ CPU :	Đang cập nhật\r\nSố nhân :	6\r\nChipset :	Apple A12 Bionic\r\nRAM :	4 GB\r\nChip đồ họa (GPU) :	Apple GPU 4 nhân\r\nCảm biến :	3D Touch\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	256 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	Không\r\nHỗ trợ thẻ nhớ tối đa :	Không\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Nguyên Khối + Thẳng\r\nChất liệu :	Viền thép, mặt lưng kính\r\nKích thước :	157.5 x 77.4 x 7.7 mm\r\nTrọng lượng :	208 g\r\nK', 35990000, 37990000, 50, '65.jpg'),
(67, 1, 1, 'iPhone 8 64GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Retina HD\r\nMặt kính màn hình :	Kính oleophobic (ion cường lực)\r\nChuẩn màn hình :	Chuẩn HD\r\nĐộ phân giải màn hình :	1334 x 750 pixels\r\nCamera Trước\r\nVideo Call :	Có\r\nĐộ phân giải :	7.0 MP\r\nCamera Sau\r\nĐộ phân giải :	12.0 MP\r\nQuay phim :	Quay phim 4K 2160p@60fps\r\nĐèn Flash :	Có\r\nCấu hình phần cứng\r\nChipset :	Apple A11 Bionic\r\nRAM :	2 GB\r\nChip đồ họa (GPU) :	Apple GPU three-core graphics\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	Không\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Thanh (thẳng) + Cảm ứng\r\nKích thước :	138.4 x 67.3 x 7.3 mm\r\nTrọng lượng :	148 g\r\nKhả năng chống nước :	Chuẩn IP67\r\nThông tin pin\r\nPin có thể tháo rời :	Không\r\nKết nối & Cổng giao tiếp\r\nKết nối USB :	Lightning\r\nCổng sạc :	Lightning\r\nJack (Input & Output) :	Lightning\r\nBăng tần 2G :	Có\r\nBăng tần 3G :	Có\r\nBăng tần 4G :	Có\r\nLoại SIM :	Nano Sim\r\nKhe cắm sim :	1 Sim\r\nWifi :	Wi-Fi 802.11 a/b/g/n/ac\r\n', 16990000, 17990000, 50, '66.jpg'),
(68, 1, 1, 'iPhone 8 Plus 64GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Widescreen LCD Multi-Touch display with IPS technology\r\nMàu màn hình :	16 Triệu màu\r\nChuẩn màn hình :	Retina HD\r\nĐộ phân giải màn hình :	1920 x 1080 pixels\r\nCông nghệ cảm ứng :	3D Touch\r\nMặt kính màn hình :	Kính cường lực\r\nCamera Trước\r\nVideo Call :	Có\r\nĐộ phân giải :	7.0 MP\r\nCamera Sau\r\nĐộ phân giải :	Dual 12.0 MP\r\nQuay phim :	2160p@24/30/60fps, 1080p@30/60/120/240fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Geo-tagging, simultaneous 4K video and 8MP image recording, touch focus, face/smile detection, HDR (photo/panorama)\r\nCấu hình phần cứng\r\nSố nhân :	6\r\nChipset :	Apple A11 Bionic\r\nRAM :	3 GB\r\nChip đồ họa (GPU) :	Apple GPU (three-core graphics)\r\nCảm biến :	Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nThẻ nhớ ngoài :	Không\r\nHỗ trợ thẻ nhớ tối đa :	Không\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Thanh (thẳng) + Cảm ứng\r\nChất liệu :	Khung', 20990000, 21990000, 50, '67.jpg'),
(69, 1, 1, 'iPhone 7 32GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Retina\r\nMàu màn hình :	16 Triệu màu\r\nChuẩn màn hình :	Chuẩn HD\r\nĐộ phân giải màn hình :	1334 x 750 pixels\r\nCông nghệ cảm ứng :	3D Touch\r\nMặt kính màn hình :	Kính oleophobic (ion cường lực)\r\nCamera Trước\r\nVideo Call :	Có\r\nThông tin khác :	Selfie ngược sáng HDR, Tự động lấy nét, Quay video Full HD, Nhận diện khuôn mặt, Panorama, Retina Flash\r\nCamera Sau\r\nĐộ phân giải :	12.0 MP\r\nQuay phim :	Quay phim 4K 2160p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Chống rung quang học\r\nCấu hình phần cứng\r\nTốc độ CPU :	2.3 GHz\r\nSố nhân :	4 Nhân\r\nChipset :	Apple A10\r\nRAM :	2 GB\r\nChip đồ họa (GPU) :	PowerVR Series7XT Plus\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	32 GB\r\nBộ nhớ còn lại :	~28 GB\r\nThẻ nhớ ngoài :	Không\r\nHỗ trợ thẻ nhớ tối đa :	Không\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Thanh (thẳng) + Cảm ứng\r\nChất liệu :	Hợp kim nhôm nguyên khối (mặt kính cong 2,5D', 11990000, 12990000, 50, '68.jpg'),
(70, 1, 1, 'iPhone 7 Plus 32GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Retina\r\nMàu màn hình :	16 Triệu màu\r\nChuẩn màn hình :	Chuẩn HD\r\nĐộ phân giải màn hình :	1334 x 750 pixels\r\nCông nghệ cảm ứng :	3D Touch\r\nMặt kính màn hình :	Kính oleophobic (ion cường lực)\r\nCamera Trước\r\nVideo Call :	Có\r\nThông tin khác :	Selfie ngược sáng HDR, Tự động lấy nét, Quay video Full HD, Nhận diện khuôn mặt, Panorama, Retina Flash\r\nCamera Sau\r\nĐộ phân giải :	12.0 MP\r\nQuay phim :	Quay phim 4K 2160p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Chống rung quang học\r\nCấu hình phần cứng\r\nTốc độ CPU :	2.3 GHz\r\nSố nhân :	4 Nhân\r\nChipset :	Apple A10\r\nRAM :	2 GB\r\nChip đồ họa (GPU) :	PowerVR Series7XT Plus\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	32 GB\r\nBộ nhớ còn lại :	~28 GB\r\nThẻ nhớ ngoài :	Không\r\nHỗ trợ thẻ nhớ tối đa :	Không\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Thanh (thẳng) + Cảm ứng\r\nChất liệu :	Hợp kim nhôm nguyên khối (mặt kính cong 2,5D', 13990000, 14990000, 50, '69.jpg'),
(71, 1, 2, 'Samsung Galaxy S10+ (512GB)', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Curved Dynamic AMOLED\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	Quad HD+\r\nĐộ phân giải màn hình :	1440 x 3040 pixels\r\nMàn hình :	6.4 inches\r\nMặt kính màn hình :	Corning Gorilla Glass 6\r\nCamera Trước\r\nĐộ phân giải :	Chính 10 MP & Phụ 8 MP\r\nThông tin khác :	Sticker AR (biểu tượng thực tế ảo), Flash màn hình, Selfie bằng cử chỉ, Nhận diện khuôn mặt, Chế độ làm đẹp, Quay video Full HD, Tự động lấy nét, Camera góc rộng, Selfie ngược sáng HDR, Chụp ảnh xoá phông, Quay phim 4K\r\nCamera Sau\r\nĐộ phân giải :	Chính 12 MP & Phụ 12 MP, 16 MP\r\nQuay phim :	Quay phim siêu chậm 960 fps, Quay phim FullHD 1080p@240fps, Quay phim 4K 2160p@60fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Chế độ Slow Motion, Zoom quang học (Camera kép), Chụp ảnh xóa phông, Super Slow Motion (quay siêu chậm), Điều chỉnh khẩu độ, Lấy nét theo pha, A.I Camera, Chế độ chụp ban đêm (ánh sáng yếu), Chế độ Time-Lapse, Tự động lấy nét, Chạm lấy nét, Nhận diện\r\nCấu hình phần cứng\r', 28990000, 29990000, 50, '70.jpg'),
(72, 1, 2, 'Samsung Galaxy Note 9 128GB', 'Pin có thể tháo rời :	Không\r\nThời gian chờ :	Đang cập nhật\r\nThời gian đàm thoại :	Đang cập nhật\r\nThời gian sạc đầy :	Đang cập nhật\r\nChế độ sạc nhanh :	Có\r\nLoại pin :	Pin chuẩn Li-Ion\r\nDung lượng pin :	4000 mAh\r\nCông nghệ pin :	Sạc pin nhanh, Tiết kiệm pin\r\nKết nối & Cổng giao tiếp\r\nBăng tần 3G :	Có\r\nBăng tần 4G :	Có\r\nGPRS/EDGE :	Có\r\nNFC :	Có\r\nBăng tần 2G :	Có\r\nCổng sạc :	USB Type-C\r\nKết nối USB :	USB Type-C\r\nCổng kết nối khác :	NFC, OTG, Screen Mirroring\r\nLoại SIM :	Nano Sim\r\nKhe cắm sim :	2 Sim\r\nWifi :	Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot\r\nGPS :	BDS, A-GPS, GLONASS\r\nBluetooth :	v5.0, A2DP, LE\r\nJack (Input & Output) :	3.5 mm\r\nMạng di động :	2G, 3G, 4G\r\nGiải trí & Ứng dụng\r\nNghe nhạc :	True\r\nXem phim :	True\r\nGhi âm :	Có\r\nFM radio :	Có\r\nĐèn pin :	Có\r\nChức năng khác :	Đèn pin, Kháng nước, kháng bụi, Sạc pin nhanh, Ghi âm cuộc gọi, Chặn cuộc gọi, Samsung Pay, Trợ lý ảo Samsung Bixby, Màn hình luôn hiển thị AOD, Mặt kính 2.5D, Chặn tin nhắn\r\nHệ điều hành\r\nHệ điều hành :	And', 18990000, 22990000, 50, '71.jpg'),
(73, 1, 2, 'Samsung Galaxy S9+ 128GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Super AMOLED\r\nMàu màn hình :	Đang cập nhật\r\nChuẩn màn hình :	Full HD\r\nĐộ phân giải màn hình :	2K (1440 x 2960 Pixels)\r\nCông nghệ cảm ứng :	Đang cập nhật\r\nMàn hình :	6.2\"\r\nMặt kính màn hình :	Corning Gorilla Glass 5\r\nCamera Trước\r\nĐộ phân giải :	8 MP\r\nThông tin khác :	Chụp bằng giọng nói, Nhận diện khuôn mặt, Chế độ làm đẹp, Quay video Full HD, Tự động lấy nét, Đèn Flash trợ sáng, Camera góc rộng, Selfie ngược sáng HDR, Tự động chụp khi nhận diện nụ cười, Selfie bằng cử chỉ\r\nCamera Sau\r\nĐộ phân giải :	2 camera 12 MP\r\nQuay phim :	Quay phim siêu chậm 960 fps, Quay phim FullHD 1080p@60fps, Quay phim 4K 2160p@60fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Zoom quang học (Camera kép),Chụp ảnh xóa phông, Chế độ chụp ban đêm (ánh sáng yếu),Điều chỉnh khẩu độ,Super Slow motion (quay siêu chậm),Tự động lấy nét,Chạm lấynét, HDR, Panorama, Chống rung quang học (OIS), Ảnh GIF, Chế độ chụp chuyên nghiệp\r\nCấu hình phần cứng\r\nTốc độ CPU :	4 nhân ', 18990000, 20990000, 50, '72.jpg'),
(74, 1, 2, 'Samsung Galaxy S8 Plus', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Super AMOLED\r\nMàu màn hình :	16 Triệu màu\r\nChuẩn màn hình :	2k\r\nĐộ phân giải màn hình :	2960 x 1440 pixels\r\nCông nghệ cảm ứng :	Đa điểm\r\nMặt kính màn hình :	Corning Gorilla Glass 5\r\nCamera Trước\r\nVideo Call :	Có\r\nĐộ phân giải :	8.0 MP\r\nThông tin khác :	Camera góc rộng, Chế độ làm đẹp, Nhận diện khuôn mặt, Selfie bằng cử chỉ, Flash màn hình\r\nCamera Sau\r\nĐộ phân giải :	Dual 12.0 MP\r\nQuay phim :	Quay phim 4K 2160p@60fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Chụp trước lấy nét sau, Chụp ảnh xóa phông, Chụp phơi sáng, Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Chống rung quang học (OIS), Chế độ chụp chuyên nghiệp\r\nCấu hình phần cứng\r\nTốc độ CPU :	4 nhân 2.3 GHz và 4 nhân 1.7 GHz\r\nSố nhân :	8 Nhân\r\nChipset :	Exynos 8895\r\nRAM :	4 GB\r\nChip đồ họa (GPU) :	Mali™ G71\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	MicroSD\r\nHỗ trợ thẻ nhớ tối đa :	256', 14490000, 17990000, 50, '73.jpg'),
(75, 1, 2, 'Samsung Galaxy A9 2018', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Super AMOLED\r\nMàu màn hình :	Đang cập nhật\r\nChuẩn màn hình :	Full HD+\r\nĐộ phân giải màn hình :	1080 x 2220 Pixels\r\nMàn hình :	6.3 inches\r\nMặt kính màn hình :	Kính cường lực Gorilla Glass\r\nCamera Trước\r\nĐộ phân giải :	24.0 MP\r\nThông tin khác :	Selfie ngược sáng HDR, Camera góc rộng, Tự động lấy nét, Quay video Full HD, Chế độ làm đẹp, Nhận diện khuôn mặt, Chụp ảnh xoá phông, Sticker AR (biểu tượng thực tế ảo)\r\nCamera Sau\r\nĐộ phân giải :	24 MP, 10 MP, 8 MP và 5 MP (4 camera)\r\nQuay phim :	Quay phim FullHD 1080p@30fps, Quay phim 4K 2160p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Chế độ Slow Motion, Chế độ Time-Lapse, A.I Camera, Super Slow motion (quay siêu chậm), Chụp ảnh xóa phông, Zoom quang học (Camera kép), Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Beautify, Chế độ chụp chuyên nghiệp\r\nCấu hình phần cứng\r\nTốc độ CPU :	4 nhân 2.2 GHz & 4 nhân 1.8 GHz\r\nSố nhân :	8\r\nChipset :	Qualcomm Snapdragon 660 8 nhâ', 8290000, 12490000, 50, '74.jpg'),
(76, 1, 3, 'Xiaomi Mi 8 Pro 8GB-128GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	Super AMOLED\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	Full HD +\r\nĐộ phân giải màn hình :	1080 x 2280 Pixels\r\nMàn hình :	6.2 inchs\r\nMặt kính màn hình :	Corning Gorilla Glass 5\r\nCamera Trước\r\nĐộ phân giải :	20.0 MP\r\nThông tin khác :	Làm đẹp, chụp xóa phông\r\nCamera Sau\r\nĐộ phân giải :	12.0 MP(Dual Camera)\r\nQuay phim :	4K\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Chụp ảnh xóa phông, Chế độ Slow Motion, Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Chống rung quang học (OIS), Beautify\r\nCấu hình phần cứng\r\nTốc độ CPU :	2.8 GHz\r\nSố nhân :	8\r\nChipset :	Snapdragon 845\r\nRAM :	8 GB\r\nChip đồ họa (GPU) :	Adreno 630\r\nCảm biến :	Vân tay siêu âm màn hình\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	128 GB\r\nBộ nhớ còn lại :	110 GB\r\nThẻ nhớ ngoài :	Không\r\nHỗ trợ thẻ nhớ tối đa :	Không\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Thanh + Thẳng\r\nChất liệu :	Viền nhôm, mặt lưng kính\r\nKích thước :	154.9 x 74.8 x7.6 mm\r\nTrọng', 14990000, 15990000, 50, '75.jpg'),
(77, 1, 3, 'Xiaomi Pocophone F1', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	IPS LCD\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	Full HD +\r\nĐộ phân giải màn hình :	1080 x 2280 Pixels\r\nMàn hình :	6.18 inches\r\nMặt kính màn hình :	Corning Gorilla Glass 3\r\nCamera Trước\r\nĐộ phân giải :	20.0 MP\r\nThông tin khác :	Làm đẹp, chụp xóa phông\r\nCamera Sau\r\nĐộ phân giải :	Camera kép 12MP+5MP\r\nQuay phim :	4K\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Chụp ảnh xóa phông, Chế độ Slow Motion, Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Chống rung quang học (OIS), Beautify\r\nCấu hình phần cứng\r\nTốc độ CPU :	2.8 GHz\r\nSố nhân :	8\r\nChipset :	Snapdragon 845\r\nRAM :	6 GB\r\nChip đồ họa (GPU) :	Adreno 630\r\nCảm biến :	Cảm biến vân tay phía sau, Cảm biến tiệm cận, Cảm biến ánh sáng\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nBộ nhớ còn lại :	55 GB\r\nThẻ nhớ ngoài :	MicroSD\r\nHỗ trợ thẻ nhớ tối đa :	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Thanh + Thẳng\r\nChất liệu :	Nhựa\r\nKích thước :	156 x 75.5 ', 7999000, 8999000, 50, '76.jpg'),
(78, 1, 3, 'Xiaomi Mi 8 Lite 128GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	IPS\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	FHD+\r\nĐộ phân giải màn hình :	1080 x 2040 Pixel\r\nMàn hình :	6.22 inches\r\nMặt kính màn hình :	Kính cường lực 2.5D\r\nCamera Trước\r\nĐộ phân giải :	24.0 MP\r\nThông tin khác :	LED flash, HDR, panorama\r\nCamera Sau\r\nĐộ phân giải :	12.0 MP + 5.0 MP\r\nQuay phim :	1080p HD\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Camera AI\r\nCấu hình phần cứng\r\nTốc độ CPU :	4x2.2 GHz Kryo 260 & 4x1.8 GHz Kryo 260\r\nSố nhân :	Octa-Core\r\nChipset :	SnapDragon 660\r\nRAM :	6 GB\r\nChip đồ họa (GPU) :	Adreno 512\r\nCảm biến :	Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	128 GB\r\nBộ nhớ còn lại :	108\r\nThẻ nhớ ngoài :	Micro SD\r\nHỗ trợ thẻ nhớ tối đa :	128 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Màn hình Tai thỏ , Full View\r\nChất liệu :	Khung kim loại + mặt kính cường lực\r\nKích thước :	156.4 x 75.8 x 7.5 mm\r\nTrọng lượng :	169 g\r\nKhả năng chống nước :	', 7490000, 8490000, 50, '77.jpg'),
(79, 1, 3, 'Xiaomi Redmi Note 6 Pro 64GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	IPS LCD\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	Full HD +\r\nĐộ phân giải màn hình :	1080 x 2280 Pixels\r\nMàn hình :	6.2 inchs\r\nMặt kính màn hình :	Corning Gorilla Glass 5\r\nCamera Trước\r\nĐộ phân giải :	Camera kép 20MP+ 2MP\r\nThông tin khác :	Làm đẹp, chụp xóa phông\r\nCamera Sau\r\nĐộ phân giải :	Camera kép 12MP+5MP\r\nQuay phim :	Full HD 1080p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Chụp ảnh xóa phông, Chế độ Slow Motion, Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Chống rung quang học (OIS), Beautify\r\nCấu hình phần cứng\r\nTốc độ CPU :	1.8 GHz\r\nSố nhân :	8\r\nChipset :	Snapdragon 636\r\nRAM :	4 GB\r\nChip đồ họa (GPU) :	Adreno 509\r\nCảm biến :	Cảm biến vân tay phía sau, Cảm biến tiệm cận, Cảm biến ánh sáng\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nBộ nhớ còn lại :	55 GB\r\nThẻ nhớ ngoài :	MicroSD\r\nHỗ trợ thẻ nhớ tối đa :	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Thanh + Thẳng\r\nChất liệu :	Ki', 5690000, 6690000, 50, '78.jpg'),
(80, 1, 3, 'Xiaomi Redmi Note 7 64GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	IPS\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	Full HD +\r\nĐộ phân giải màn hình :	1080 x 2340 Pixels\r\nMàn hình :	6.3 inches\r\nMặt kính màn hình :	Corning Gorilla Glass 5\r\nCamera Trước\r\nĐộ phân giải :	13.0 MP\r\nThông tin khác :	Mở khóa bằng gương mặt\r\nCamera Sau\r\nĐộ phân giải :	48 MP+ 5 MP\r\nQuay phim :	1080p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	HDR,chụp ảnh 48 MP\r\nCấu hình phần cứng\r\nTốc độ CPU :	2.2 GHz\r\nSố nhân :	8\r\nChipset :	Snap Dragon 660\r\nRAM :	4 GB\r\nChip đồ họa (GPU) :	Adreno 512\r\nCảm biến :	có\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	Micro SD\r\nHỗ trợ thẻ nhớ tối đa :	Đang cập nhật\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Nguyên khối, mặt kính cong 2.5D\r\nChất liệu :	Nhựa (mặt kính cong 2,5D)\r\nKích thước :	159.2 x 75.2 x 8.1 mm\r\nTrọng lượng :	186 G\r\nKhả năng chống nước :	Không\r\nThông tin pin\r\nLoại pin :	Li-polymer\r\nDung lượng pin :	4000 mAh\r\nPin có th', 4990000, 5990000, 50, '79.jpg'),
(81, 1, 4, 'OPPO F11 Pro 128GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	LTPS TFT\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	Full HD +\r\nĐộ phân giải màn hình :	1080 x 2340 Pixels\r\nMàn hình :	6.53 inchs\r\nMặt kính màn hình :	Corning Gorilla Glass 5\r\nCamera Trước\r\nĐộ phân giải :	16.0 MP\r\nThông tin khác :	Làm đẹp , Chụp ngược sáng..v.v.\r\nCamera Sau\r\nĐộ phân giải :	48 MP+ 5 MP\r\nQuay phim :	Full HD 1080p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Panorama, HDR,Làm Đẹp,…v..v.\r\nCấu hình phần cứng\r\nTốc độ CPU :	2.1 GHz\r\nSố nhân :	8\r\nChipset :	MTK P70\r\nRAM :	6 GB\r\nChip đồ họa (GPU) :	Mali-G72 MP3\r\nCảm biến :	Có\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	128 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	Micro SD\r\nHỗ trợ thẻ nhớ tối đa :	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Nguyên khối, màn hình vô cực, tỷ lệ hiển thị cao\r\nChất liệu :	Nhựa Polycarbonate\r\nKích thước :	161.3 x 76.1 x 8.8 mm\r\nTrọng lượng :	190 G\r\nKhả năng chống nước :	Không\r\nThông tin pin\r\nLoại pin :	Li-Ion, sạc nhanh\r', 8490000, 9490000, 50, '80.jpg'),
(82, 1, 4, 'OPPO F11', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	IPS\r\nMàu màn hình :	16 Triệu\r\nChuẩn màn hình :	Full HD +\r\nĐộ phân giải màn hình :	1080 x 2340 Pixels\r\nMàn hình :	6.53 inchs\r\nMặt kính màn hình :	Corning Gorilla Glass 5\r\nCamera Trước\r\nĐộ phân giải :	16.0 MP\r\nThông tin khác :	Làm đẹp , Chụp ngược sáng..v.v.\r\nCamera Sau\r\nĐộ phân giải :	48 MP+ 5 MP\r\nQuay phim :	Full HD 1080p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Panorama, HDR,Làm Đẹp,…v..v.\r\nCấu hình phần cứng\r\nTốc độ CPU :	2.1 GHz\r\nSố nhân :	8\r\nChipset :	MTK P70\r\nRAM :	6 GB\r\nChip đồ họa (GPU) :	Mali-G72 MP3\r\nCảm biến :	Có\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	Micro SD\r\nHỗ trợ thẻ nhớ tối đa :	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Nguyên khối, màn hình vô cực, tỷ lệ hiển thị cao\r\nChất liệu :	Nhựa Polycarbonate\r\nKích thước :	162 x 76.1 x 8.3 mm\r\nTrọng lượng :	188 G\r\nKhả năng chống nước :	Không\r\nThông tin pin\r\nLoại pin :	Li-Ion, sạc nhanh\r\nDung lư', 7290000, 7290000, 50, '81.jpg'),
(83, 1, 4, 'OPPO F9', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	LTPS LCD\r\nMàu màn hình :	16 triệu màu\r\nChuẩn màn hình :	Full HD+\r\nĐộ phân giải màn hình :	1080 x 2340 pixels\r\nMàn hình :	6.3 inch\r\nMặt kính màn hình :	Corning Gorilla Glass 6\r\nCamera Trước\r\nĐộ phân giải :	25 MP\r\nThông tin khác :	Nhận diện khuôn mặt, Quay video HD, Sticker AR (biểu tượng thực tế ảo), Công nghệ Selfie A.I Beauty\r\nCamera Sau\r\nĐộ phân giải :	16 MP và 2 MP (2 camera)\r\nQuay phim :	Quay phim HD 720p@24fps, Quay phim FullHD 1080p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Chụp ảnh xóa phông, Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Beautify\r\nCấu hình phần cứng\r\nTốc độ CPU :	2.0 Ghz\r\nSố nhân :	8 nhân\r\nChipset :	MediaTek Helio P60\r\nRAM :	4 GB\r\nChip đồ họa (GPU) :	Mali-G72 MP3\r\nCảm biến :	Có\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	Micro SD\r\nHỗ trợ thẻ nhớ tối đa :	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Nguyên khối\r\nChấ', 6490000, 6490000, 50, '82.jpg'),
(84, 1, 4, 'OPPO A7', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	IPS LCD\r\nMàu màn hình :	16 triệu màu\r\nChuẩn màn hình :	HD+\r\nĐộ phân giải màn hình :	1520 x 720 Pixel\r\nMàn hình :	6.2 inches\r\nMặt kính màn hình :	Mặt kính cong 2.5D\r\nCamera Trước\r\nĐộ phân giải :	16.0 MP\r\nThông tin khác :	Chế độ làm đẹp, Sticker AR (biểu tượng thực tế ảo)\r\nCamera Sau\r\nĐộ phân giải :	13.0 MP + 2.0 MP\r\nQuay phim :	1080p@30fps\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Làm đẹp thông minh AI, Tự động lấy nét, Chạm lấy nét, HDR, Panorama\r\nCấu hình phần cứng\r\nTốc độ CPU :	1.8 Ghz\r\nSố nhân :	8\r\nChipset :	Qualcomm Snapdragon 450\r\nRAM :	4 GB\r\nChip đồ họa (GPU) :	Adreno 506\r\nCảm biến :	Có\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	64 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	Micro SD\r\nHỗ trợ thẻ nhớ tối đa :	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Nguyên Khối\r\nChất liệu :	Nhựa\r\nKích thước :	155.9 x 75.4 x 8.1 mm\r\nTrọng lượng :	158 g\r\nKhả năng chống nước :	Không\r\nThông tin pin\r\nLoại pin :	Li-Ion\r\nDun', 5490000, 5490000, 50, '83.jpg'),
(85, 1, 4, 'Oppo A3s 32GB', 'Thông số kỹ thuật chi tiết\r\nMàn hình\r\nCông nghệ màn hình :	IPS LCD\r\nMàu màn hình :	16 triệu màu\r\nChuẩn màn hình :	HD+\r\nĐộ phân giải màn hình :	720 x 1520 pixels\r\nCông nghệ cảm ứng :	Có\r\nMàn hình :	6.2\"\r\nMặt kính màn hình :	Kính cường lực Gorilla Glass 3\r\nCamera Trước\r\nĐộ phân giải :	8 MP\r\nThông tin khác :	Tự động lấy nét, Công nghệ Selfie A.I Beauty\r\nCamera Sau\r\nĐộ phân giải :	13 MP + 2 MP\r\nQuay phim :	Có\r\nĐèn Flash :	Có\r\nChụp ảnh nâng cao :	Chụp ảnh xóa phông, Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama\r\nCấu hình phần cứng\r\nTốc độ CPU :	1.8 GHz\r\nSố nhân :	8 nhân\r\nChipset :	Qualcomm Snapdragon 450\r\nRAM :	3 GB\r\nChip đồ họa (GPU) :	Adreno 506\r\nCảm biến :	Có\r\nBộ nhớ & Lưu trữ\r\nDanh bạ lưu trữ :	Không giới hạn\r\nROM :	32 GB\r\nBộ nhớ còn lại :	Đang cập nhật\r\nThẻ nhớ ngoài :	MicroSD\r\nHỗ trợ thẻ nhớ tối đa :	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng :	Nguyên khối\r\nChất liệu :	Nhựa\r\nKích thước :	156.2 x 75.6 x 8.2 mm\r\nTrọng lượng :	168 g\r\nKhả năng chống nước :	Không\r\nThông ', 4090000, 4090000, 50, '84.jpg'),
(86, 1, 5, 'LG G6 Cũ - Fullbox', 'Thông tin chung\r\nHệ điều hành:	Android OS, v7.0 (Nougat)\r\nNgôn ngữ:	Đa ngôn ngữ hỗ trợ Tiếng Việt\r\nMàn hình\r\nLoại màn hình:	IPS LCD\r\nMàu màn hình:	16 triệu màu\r\nChuẩn màn hình:	FullVision\r\nĐộ phân giải:	1440 x 2880 pixels (mật độ điểm ảnh ~564 ppi)\r\nMàn hình rộng:	5.7\r\nCông nghệ cảm ứng:	Cảm ứng điện dung đa điểm\r\nChụp hình & Quay phim\r\nCamera sau:	13 MP (f/1.8) + 13 MP (f/2.4)\r\nCamera trước:	5 MP\r\nĐèn Flash:	Có\r\nTính năng camera:	Tự động lấy nét, nhận diện khuôn mặt, chụp ảnh HDR, Panorama\r\nQuay phim:	2160p@30fps, 1080p@30/60fps\r\nVideocall:	Có\r\nCPU & RAM\r\nTốc độ CPU:	Quad-core (2x2.35 GHz Kryo & 2x1.6 GHz Kryo)\r\nSố nhân:	4 nhân\r\nChipset:	Qualcomm MSM8996 Snapdragon 821\r\nRAM:	4 GB\r\nChip đồ họa (GPU):	Adreno 530\r\nBộ nhớ & Lưu trữ\r\nDanh bạ:	Không giới hạn\r\nBộ nhớ trong (ROM):	32 GB - 64 GB\r\nThẻ nhớ ngoài:	microSD\r\nHỗ trợ thẻ tối đa:	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng:	Cảm ứng\r\nKích thước:	148.9 x 71.9 x 7.9 mm\r\nTrọng lượng (g):	163\r\nThông tin pin\r\nLoại pin:	Li-Ion\r\nDung lượng pin:', 2950000, 3950000, 50, '85.jpg'),
(87, 1, 5, 'LG V20 Cũ - Fullbox (Có 4G/LTE)', 'Thông tin chung\r\nHệ điều hành:	Android 7.0\r\nNgôn ngữ:	Đa ngôn ngữ, có hỗ trợ Tiếng Việt\r\nMàn hình\r\nLoại màn hình:	IPS LCD\r\nMàu màn hình:	16 triệu màu\r\nChuẩn màn hình:	2K\r\nĐộ phân giải:	1440 x 2560 pixels , mật độ điểm ảnh ~ 513 ppi\r\nMàn hình rộng:	5.7\r\nCông nghệ cảm ứng:	Cảm ứng đa điểm (10 điểm)\r\nChụp hình & Quay phim\r\nCamera sau:	16 MP + 8MP\r\nCamera trước:	5 MP\r\nĐèn Flash:	Có\r\nTính năng camera:	Tự động lấy nét, nhận diện khuôn mặt, chụp ảnh HDR, Panorama\r\nQuay phim:	2160p-30fps, 1080p-30fps, 720p-120fps\r\nVideocall:	Có\r\nCPU & RAM\r\nTốc độ CPU:	Quad-core 2x2.15 GHz Kryo & 2x1.6 GHz Kryo\r\nSố nhân:	4 nhân\r\nChipset:	Qualcomm MSM8996 S820\r\nRAM:	4 GB\r\nChip đồ họa (GPU):	Adreno 530\r\nBộ nhớ & Lưu trữ\r\nDanh bạ:	Không giới hạn\r\nBộ nhớ trong (ROM):	32 GB - 64 GB\r\nThẻ nhớ ngoài:	microSD\r\nHỗ trợ thẻ tối đa:	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng:	Cảm ứng\r\nKích thước:	159,7 x 78,1 x 7,6 mm\r\nTrọng lượng (g):	174\r\nThông tin pin\r\nLoại pin:	Li-Ion\r\nDung lượng pin:	3200 mAh\r\nPin có thể tháo rời:	Có\r\nK', 3250000, 3500000, 50, '88.jpg'),
(88, 1, 5, 'LG V30 Cũ (Hàn Quốc, Mỹ)', 'Thông tin chung\r\nHệ điều hành:	Android 7.1\r\nNgôn ngữ:	Đa ngôn ngữ\r\nMàn hình\r\nLoại màn hình:	P-OLED\r\nMàu màn hình:	16 triệu màu\r\nChuẩn màn hình:	2K\r\nĐộ phân giải:	1440 x 2880\r\nMàn hình rộng:	6\r\nCông nghệ cảm ứng:	Cảm ứng điện dung đa điểm\r\nChụp hình & Quay phim\r\nCamera sau:	16 MP - 13 MP\r\nCamera trước:	5 MP\r\nĐèn Flash:	Có\r\nTính năng camera:	Tự động lấy nét, nhận diện khuôn mặt, chụp ảnh HDR, Panorama\r\nQuay phim:	Quay phim 4K 2160p@30fps\r\nVideocall:	Có\r\nCPU & RAM\r\nTốc độ CPU:	\r\nSố nhân:	8 nhân\r\nChipset:	Qualcomm Snapdragon 835\r\nRAM:	4 GB\r\nChip đồ họa (GPU):	Adreno 540\r\nBộ nhớ & Lưu trữ\r\nDanh bạ:	Không giới hạn\r\nBộ nhớ trong (ROM):	64 GB\r\nThẻ nhớ ngoài:	MicroSD\r\nHỗ trợ thẻ tối đa:	256 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng:	Nguyên khối\r\nKích thước:	151.7 x 75.4 x 7.4 mm\r\nTrọng lượng (g):	158\r\nThông tin pin\r\nLoại pin:	Pin chuẩn Li-Ion\r\nDung lượng pin:	3300 mAh\r\nPin có thể tháo rời:	Không\r\nKết nối & Cổng giao tiếp\r\n3G:	3G\r\n4G:	4G LTE Cat 16\r\nLoại Sim:	Nano SIM\r\nKhe gắn Sim:	1 SIM\r\nWifi:	Wi-F', 4450000, 6450000, 50, '89.jpg'),
(89, 1, 5, 'LG G7 ThinQ Cũ - Fullbox', 'Thông tin chung\r\nHệ điều hành:	Android 8.0 Oreo\r\nNgôn ngữ:	Đa ngôn ngữ hỗ trợ Tiếng Việt\r\nMàn hình\r\nLoại màn hình:	IPS LCD\r\nMàu màn hình:	16 triệu màu\r\nChuẩn màn hình:	QHD+\r\nĐộ phân giải:	1440 x 3120 pixels\r\nMàn hình rộng:	6.1\r\nCông nghệ cảm ứng:	Cảm ứng đa điểm\r\nChụp hình & Quay phim\r\nCamera sau:	Dual 16 MP\r\nCamera trước:	8 MP\r\nĐèn Flash:	Có\r\nTính năng camera:	A.I Camera, Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama\r\nQuay phim:	Quay phim FullHD 1080p@30fps, Quay phim 4K 2160p@30fps\r\nVideocall:	Có\r\nCPU & RAM\r\nTốc độ CPU:	Octa-core (4x2.8 GHz Kryo 385 Gold & 4x1.7 GHz Kryo 385 Silver)\r\nSố nhân:	8 nhân\r\nChipset:	Snapdragon 845\r\nRAM:	4 GB - 6 GB\r\nChip đồ họa (GPU):	Adreno 630\r\nBộ nhớ & Lưu trữ\r\nDanh bạ:	Không giới hạn\r\nBộ nhớ trong (ROM):	64 GB - 128 GB\r\nThẻ nhớ ngoài:	microSD\r\nHỗ trợ thẻ tối đa:	512 GB\r\nThiết kế & Trọng lượng\r\nKiểu dáng:	Thanh + Cảm ứng\r\nKích thước:	153.2 x 71.9 x 7.9 mm\r\nTrọng lượng (g):	162\r\nThông tin pin\r\nLoại pin:	Li-Po\r\nDung lượng pin:	3000 mAh\r', 6250000, 8950000, 50, '86.jpg'),
(90, 1, 5, 'LG V40 cũ', 'Thông tin chung\r\nHệ điều hành:	Android 8.1 (Oreo); LG UX 7.1\r\nNgôn ngữ:	Tiếng Việt, Tiếng Anh, Đa ngôn ngữ\r\nMàn hình\r\nLoại màn hình:	P-OLED\r\nMàu màn hình:	16 triệu màu\r\nChuẩn màn hình:	P-OLEDl, 2K+ (1440 x 3120 Pixels), 6.4 inch, 16 triệu màu\r\nĐộ phân giải:	1440 x 3120 Pixels\r\nMàn hình rộng:	6.4 inch\r\nCông nghệ cảm ứng:	Cảm ứng điện dung đa điểm\r\nChụp hình & Quay phim\r\nCamera sau:	12MP, 12MP và 16MP (3 camera)\r\nCamera trước:	8MP và 5MP\r\nĐèn Flash:	Có\r\nTính năng camera:	Zoom quang học (Camera kép), Chế độ chụp ban đêm (ánh sáng yếu), A.I Camera, Lấy nét theo pha, Super Slow motion (quay siêu chậm), Tự động lấy nét, Chạm lấy nét, Nhận diện khuôn mặt, HDR, Panorama, Chống rung quang học (OIS), Beautify, Ảnh GIF\r\nQuay phim:	Quay phim 2160p @30/60fps, 1080p @30/60/240fps\r\nVideocall:	Có\r\nCPU & RAM\r\nTốc độ CPU:	Octa-core (4x2,7 GHz Kryo 385 Gold & 4x1,7 GHz Kryo 385 Silver)\r\nSố nhân:	8 nhân\r\nChipset:	Qualcomm SDM845 Snapdragon 845 (10nm)\r\nRAM:	6GB\r\nChip đồ họa (GPU):	Adreno 630\r\nBộ nhớ & Lưu', 8450000, 8950000, 50, '87.jpg'),
(91, 2, 1, 'Ốp lưng kiêm sạc dự phòng cho iPhone 7, 7 Plus', 'Mô tả Ốp lưng kiêm sạc dự phòng cho iPhone 7, 7 Plus\r\nỐp lưng kiêm sạc dự phòng cho iPhone 7, 7 Plus giá rẻ nhất tại Hà Nội, TPHCM. Bảo hành dài hạn lên tới 12 tháng. Đặt mua ngay ốp lưng kiêm sạc dự phòng cho iPhone tại MobileCity để nhận được mức giá tốt nhất và các ưu đãi đặc biệt hấp dẫn.\r\n\r\nTrên thị trường hiện nay có rất nhiều loại sạc dự phòng, nhưng cần phải gắn dây kết nối để sạc, rất bất tiện trong lúc sử dụng điện thoại hoặc di chuyển, không thể bỏ túi lúc sạc, không thể sử dụng thoải mái lúc sạc vì luôn có dây kết nối. MobileCity đã tìm ra một giải pháp sạc dự phòng thông minh và tiện dụng cho Khách hàng sử dụng điện thoại iPhone 7,7 Plus.\r\n\r\nBạn có thể sạc máy iPhone 7, 7 Plus mọi lúc mọi nơi và sạc bất kỳ lúc nào bạn muốn. Chỉ cần lắp máy iPhone của bạn vào ốp lưng bấm nút và sạc, không cần kết nối bất kỳ sợi dây nào, không cần tìm ổ cắm điện. Trong lúc sạc chiếc điện thoại của quý khách vẫn sử dụng bình thường tất cả các chức năng. Đặc biệt quý khách đi du lịch, công tác', 360000, 360000, 50, '90.jpg'),
(92, 2, 1, 'Ốp lưng iPhone 6, 6S', 'Mô tả Ốp lưng iPhone 6, 6S\r\nỐp lưng iPhone 6, 6S Đẹp, Độc, Dễ thương giá Rẻ nhất tại Hà Nội, TPHCM. Ốp lưng iPhone 6S, 6 Silicon, nhựa mềm, nhựa cứng, kim loại... giá chỉ từ 50.000đ.\r\n\r\nCùng với sự phát triển của điện thoại iPhone 6, 6S là sự đổi mới, phát triển rất nhiều các phụ kiện đi kèm: bao da, ốp lưng iPhone, dán màn hình cho iPhone. Trong đó bao da, ốp lưng luôn luôn được chú ý nhiều hơn (vừa có tính năng bảo vệ máy lại có tính năng thời trang), ngay bản thân Apple cũng đang tham gia vào quá trình sản xuất ốp lưng chính hãng cho iPhone. Riêng về ốp lưng iPhone 6, ốp lưng iPhone 6s (và viền bao) có thể được sản xuất bởi một trong các chất liệu sau với những ưu và nhược điểm riêng của nó.', 50000, 50000, 50, '91.jpg'),
(93, 2, 1, 'Ốp lưng iPhone 5, 5S', 'Mô tả Ốp lưng iPhone 5, 5S\r\nỐp lưng iPhone 5, 5S Đẹp, Độc, Dễ thương giá Rẻ nhất tại Hà Nội, TPHCM. Ốp lưng iPhone 5S, 5 Silicon, nhựa mềm, nhựa cứng, kim loại. Giá chỉ từ 50.000đ.\r\n\r\nỐp lưng iPhone 5 và 5S có khá nhiều loại khác nhau về kiểu dáng, mẫu mã, màu sắc, chất liệu. Có thể vì điều đó khiến bạn sẽ cảm thấy khó khăn khi tìm mua ốp lưng cho điện thoại iPhone 5, 5S. Để giúp bạn có thể chọn được mẫu ốp lưng ưng ý, bài viết này sẽ điểm lại giá bán và đặc điểm của 5 loại ốp lưng iPhone Hot nhất hiện nay.', 50000, 50000, 50, '92.jpg'),
(94, 2, 1, 'Ốp lưng iPhone 6 Plus, 6S Plus', 'Mô tả Ốp lưng iPhone 6 Plus, 6S Plus\r\nỐp lưng iPhone 6 Plus, 6S Plus Đẹp, Độc, Dễ thương giá Rẻ nhất tại Hà Nội, TPHCM. Ốp lưng iPhone 6S Plus, 6 Plus Silicon, nhựa mềm, nhựa cứng, kim loại... giá chỉ từ 50.000đ.\r\n\r\nCùng với sự phát triển của điện thoại iPhone 6 Plus, 6S Plus là sự đổi mới, phát triển rất nhiều các phụ kiện đi kèm: bao da, ốp lưng iPhone, dán màn hình cho iPhone. Trong đó bao da, ốp lưng luôn luôn được chú ý nhiều hơn (vừa có tính năng bảo vệ máy lại có tính năng thời trang), ngay bản thân Apple cũng đang tham gia vào quá trình sản xuất ốp lưng chính hãng cho iPhone. Riêng về ốp lưng iPhone 6 Plus, ốp lưng iPhone 6s Plus (và viền bao) có thể được sản xuất bởi một trong các chất liệu sau với những ưu và nhược điểm riêng của nó.', 50000, 50000, 50, '93.jpg'),
(95, 2, 1, 'Ốp lưng iPhone 8', 'Mô tả Ốp lưng iPhone 8\r\nỐp lưng iPhone 8 Đẹp, Độc, Dễ thương giá Rẻ nhất tại Hà Nội, TPHCM. Ốp lưng iPhone 8 Silicon, nhựa mềm, nhựa cứng, kim loại... giá chỉ từ 50.000đ.\r\n\r\nCùng với sự phát triển của điện thoại iPhone 8 là sự đổi mới, phát triển rất nhiều các phụ kiện đi kèm: bao da, ốp lưng iPhone, dán màn hình cho iPhone. Trong đó bao da, ốp lưng luôn luôn được chú ý nhiều hơn (vừa có tính năng bảo vệ máy lại có tính năng thời trang), ngay bản thân Apple cũng đang tham gia vào quá trình sản xuất ốp lưng chính hãng cho iPhone. Riêng về ốp lưng iPhone 8 (và viền bao) có thể được sản xuất bởi một trong các chất liệu sau với những ưu và nhược điểm riêng của nó.', 50000, 50000, 50, '94.jpg'),
(96, 2, 2, 'Ốp lưng Samsung Galaxy S10 Plus', 'Mô tả Ốp lưng Samsung Galaxy S10 Plus\r\nỐp lưng Samsung Galaxy S10 Plus Đẹp, Đa dạng mẫu mã, Giá rẻ tại Hà Nội, TPHCM. Mobilecity cung cấp những mẫu ốp lưng Samsung Galaxy S10 Plus giá rẻ nhất chỉ từ 50k.\r\n\r\nTại sao nên mua Ốp lưng Samsung Galaxy S10 Plus ?\r\nSamsung Galaxy S10 Plus là 1 trong những chiếc smartphone mới nhất gần đây của Samsung với thiết kế đột phá và hiệu năng tốt, được rất nhiều người dùng và các tín đồ công nghệ yêu thích và chọn mua. Chiếc smartphone đều có mức giá trên 30 triệu đồng, điều đó đòng nghĩa với việc các linh kiện của máy cũng có giá cao. Nếu chẳng may làm rơi hoặc máy bị va chạm mạnh với vật cứng thì bạn phải bỏ ra một số tiền khá lớn để sửa chữa. Nhưng với ốp lưng Samsung Galaxy S10 Plus chất lượng từ Mobile City thì điều đó hoàn toàn không bao giờ xảy ra. Hãy tham khảo ngay các mẫu Ốp lưng dưới đây hoặc đến trực tiếp chi nhánh tại Hà Nội, TPHCM để có thể lựa chọn cho mình chiếc phụ kiện ưng ý, phù hợp nhất nhé.\r\n\r\nCó những loại Ốp lưng Samsung Galaxy S', 50000, 50000, 50, '95.jpg'),
(97, 2, 2, 'Ốp lưng Samsung Galaxy A8s', 'Mô tả Ốp lưng Samsung Galaxy A8s\r\nỐp lưng Samsung Galaxy A8s chính hãng, đảm bảo giá rẻ nhất tại Hà Nội và TP. HCM. Là một phụ kiện gần như không thể thiếu trên chiếc điện thoại của bạn với chức năng bảo vệ, chiếc ốp lưng Samsung Galaxy A8s sẽ là thiết bị bảo vệ tốt nhất chiếc điện thoại của bạn để tránh những bụi bẩn hay xước.', 50000, 50000, 50, '96.jpg'),
(98, 2, 2, 'Ốp lưng Samsung Galaxy S10e', 'Mô tả Ốp lưng Samsung Galaxy S10e\r\nỐp lưng Samsung Galaxy S10e chính hãng, đảm bảo giá rẻ nhất tại Hà Nội và TP. HCM. Là một phụ kiện gần như không thể thiếu trên chiếc điện thoại của bạn với chức năng bảo vệ, chiếc ốp lưng Samsung Galaxy S10e sẽ là thiết bị bảo vệ tốt nhất chiếc điện thoại của bạn để tránh những bụi bẩn hay xước.', 50000, 50000, 50, '97.jpg'),
(99, 2, 2, 'Ốp lưng Samsung Galaxy A6s', 'Mô tả Ốp lưng Samsung Galaxy A6s\r\nỐp lưng Samsung Galaxy A6s giá RẺ, chất lượng đảm bảo nhất tại Hà Nội, HCM, Đà Nẵng. Mua ốp lưng Samsung Galaxy A6s đẹp chỉ từ 50.000đ.', 50000, 50000, 50, '98.jpg'),
(100, 2, 2, 'Ốp lưng Samsung Galaxy A9s', 'Mô tả Ốp lưng Samsung Galaxy A9s\r\nỐp lưng Samsung Galaxy A9s đẹp, RẺ nhất Hà Nội, HCM, Đà Nẵng. Mua ốp lưng Samsung Galaxy A9s chất lượng, chính hãng ngay tại Mobile City. \r\n\r\nMobile City chuyên cung cấp ốp lưng Samsung Galaxy A9s đẹp mà RẺ, chính hãng nhất Hà Nội,HCM. Ốp lưng Samsung Galaxy A9s nhiều mẫu mã mà giá chỉ 50.000đ.', 50000, 50000, 50, '99.jpg'),
(101, 2, 3, 'Dán Cường Lực Xiaomi Mi Max 3', 'Mô tả Dán Cường Lực Xiaomi Mi Max 3\r\nDán Cường Lực Xiaomi Mi Max 3 giá rẻ, chất lượng tại Hà Nội, TP.HCM. Tấm dán cường lực Xiaomi Mi Max 3 là phụ kiện không thể giúp bảo vệ chiếc điện thoại của bạn an toàn hơn.\r\n\r\nMobileCity chuyên cung cấp dịch vụ dán cường lực Xiaomi Mi Max 3 giá rẻ, đảm bảo chất lượng tốt nhất. Nếu bạn đang sở hữu chiếc Xiaomi Mi Max 3 hãy nhanh chóng bảo vệ chiếc điện thoại của mình bằng cách dán cường lực và mua ốp lưng Xiaomi Mi Max 3 nhé.', 120000, 120000, 50, '100.jpg'),
(102, 2, 3, 'Ốp lưng Xiaomi Mi 9 SE', 'Mô tả Ốp lưng Xiaomi Mi 9 SE\r\nỐp lưng Xiaomi Mi 9 SE đẹp nhất và cực độc đáo tại Hà Nội, Tp.HCM, Đà Nẵng. Hệ thống cửa hàng điện thoại MobileCity sẽ cung cấp cho bạn những mẫu ốp cực độc đáo và lạ mắt với mức giá cực rẻ chỉ từ 50.000đ.\r\n\r\nTại sao phải mua ốp lưng Xiaomi Mi 9 SE\r\nXiaomi là hãng sản xuất điện thoại nổi tiếng nhất Trung Quốc. Mới đây, họ đã ra mắt sản phẩm cao cấp nhất năm 2019 là Xiaomi Mi 9, Xiaoimi Mi 9 SE,..v.v. Xiaomi cũng không quên ra mắt những chiếc ốp độc và lạ, Ốp lưng vừa đẹp mắt vừa bảo vệ rất tốt máy. Giả sử nếu một ngày nào đó bạn vô tình làm rơi sản phẩm của mình xuống đất, thiết bị của bạn có thể gặp vấn đề vỡ nát hay ngừng hoạt động. Việc thay thế và sửa chữa cũng sẽ rất tốn kém. Chính vì thế mà MobileCity đáp ứng nhu cầu của người dùng bằng việc bán những chiếc ốp lưng Xiaomi Mi 9 SE đẹp nhất, độc nhất với giá thành cực rẻ chỉ từ 50.000đ. Bạn hãy tham khảo những mẫu ốp dưới đây để có thể lựa chọn cho mình những phụ kiện tốt nhất tại hệ thống cửa hàng Mob', 50000, 50000, 50, '101.jpg'),
(103, 2, 3, 'Ốp lưng Xiaomi Redmi Note 7', 'Mô tả Ốp lưng Xiaomi Redmi Note 7\r\nỐp lưng Xiaomi Redmi Note 7 giá RẺ nhất Hà Nội, Đà Nẵng, TP HCM. Mua Ốp lưng Xiaomi Redmi Note 7 Uy tín, BH 12 Tháng Chính hãng.\r\n\r\nỐp lưng Xiaomi Redmi Note 7 có tác dụng gì?\r\nChắc chắn ốp lưng Xiaomi Redmi Note 7 sẽ làm được những điều tuyệt vời nhất dành cho cả bạn và cả chính chiếc smatphone Xiaomi Redmi Note 7 này. Đó là điều mà MobileCity chúng tôi cam kết, chỉ cần trang bị thêm một phụ kiện nhỏ như ốp lưng Xiaomi Redmi Note 7 là bạn đã có thể xua tan mọi lo lắng mà không cần thêm phụ kiện khác như bao da. Ốp lưng Xiaomi Redmi Note 7 hàng chính hãng có thể làm hài lòng tất cả khách hàng dù là khó tính, với tính năng vượt trội về sự bảo vệ máy chống sốc, xước, tay ôm mềm mại tạo độ chắc chắn cho tay cầm.', 50000, 50000, 50, '102.jpg'),
(104, 2, 3, 'Ốp lưng Xiaomi Play', 'Mô tả Ốp lưng Xiaomi Play\r\nỐp lưng Xiaomi Play chính hãng, đảm bảo giá rẻ nhất tại Hà Nội và TP. HCM. Là một phụ kiện gần như không thể thiếu trên chiếc điện thoại của bạn với chức năng bảo vệ, chiếc ốp lưng Xiaomi Play sẽ là thiết bị bảo vệ tốt nhất chiếc điện thoại của bạn để tránh những bụi bẩn hay xước.\r\n\r\nTác dụng của Ốp lưng Xiaomi Play như thế nào ?\r\nVới khá nhiều những chiếc điện thoại thông minh và cao cấp như hiện nay có kiểu dáng độc đáo và tính năng hấp dẫn thì nhà sản xuất Xiaomi cũng đã cho ra mắt những phụ kiện vô cùng tiện ích nhưng cũng không kém phần bắt mắt. Chiếc ốp lưng Xiaomi Play cũng là một trong các phụ kiện giúp bảo vệ cho chiếc điện thoại của bạn tốt nhất.', 50000, 50000, 50, '103.jpg'),
(105, 2, 3, 'Ốp lưng Xiaomi Redmi 6A', 'Mô tả Ốp lưng Xiaomi Redmi 6A\r\nMua ốp lưng Xiaomi Redmi 6A giá RẺ, độc, Đẹp nhất tại Hà Nội,HCM, Đà Nẵng. Ốp lưng Xiaomi Redmi 6A tại Mobile City có chất lượng tốt, nhiều mẫu mã,..\r\n\r\nDùng Ốp lưng Xiaomi Redmi 6A có lợi ích gì?\r\nKhách hàng sau khi mua máy chỉ cần trang bị thêm một phụ kiện nhỏ như ốp lưng Xiaomi Redmi 6A là bạn đã có thể xua tan mọi lo lắng mà không cần thêm phụ kiện khác như bao da. Với tính năng vượt trội sự để bảo vệ máy chống sốc, xước, tay ôm mềm mại tạo độ chắc chắn cho tay cầm giúp cho ốp lưng Xiaomi Redmi 6A có thể làm hài lòng tất cả khách hàng dù là khó tính nhất.', 50000, 50000, 50, '104.jpg'),
(106, 2, 4, 'Dán cường lực Oppo F1S', 'Mô tả Dán cường lực Oppo F1S\r\nDán cường lực Oppo F1S chất lượng, giá rẻ. Kính cường lực Oppo F1S được nhập khẩu chính hãng, có độ bền gấp 20 lần kính thường, giúp máy tránh được những rủi do đáng tiếc trong quá trình khi sử dụng.\r\n\r\nĐể bảo vệ màn hình cho \"dế yêu\" tốt nhất, MobileCity cung cấp miếng dán cường lực F1S với độ chịu lực 9H mà không ảnh hưởng tới hiển thị cũng như độ nhạy cảm ứng. Tấm dán cường lực Oppo F1S có độ bền cao, độ dày vừa phải sẽ bảo vệ an toàn chiếc smartphone của bạn.\r\n\r\nTác dụng tuyệt vời của miếng dán cường lực Oppo F1S\r\nKính cường lực J3 Pro được thiết kế có độ dày 0.2 đến 0.4mm, độ cứng 9H, bền hơn tới 20 lần so với miếng dán thường. Kính dán cường lực Oppo F1S cấu tạo bởi những lớp kính kết lại với nhau thành nhiều lớp bên trong như cảm quang, lớp màu sắc, lớp chống vỡ... Với chất kết dính silicon mạnh mẽ, quá trình dán dễ dàng và không ảnh hưởng tới độ nhạy cảm ứng.\r\n\r\nĐặc biệt, dán cường lực Oppo F1S còn giúp hiển thị tốt hơn cho màn hình dưới ánh sáng t', 100000, 100000, 50, '105.jpg'),
(107, 2, 4, 'Dán cường lực Oppo A71', 'Mô tả Dán cường lực Oppo A71\r\nTấm Dán cường lực Oppo A71 chính hãng, chất lượng tốt, giá rẻ tại Hà Nội, TP.HCM. Dán cường lực Oppo A71 là phụ kiện không thể thiếu của Oppo A71, gúp máy của bạn được an toàn hơn trong nhiều trường hợp vô tình như đánh rơi máy hay va đập. Ngoài ra kính còn giúp máy bạn chông nước và bụi bẩn và máy, không bám vân tay trên màn hình, gữ cho màn hình luôn mới.', 100000, 100000, 50, '106.jpg'),
(108, 2, 4, 'Dán cường lực Oppo A77', 'Mô tả Dán cường lực Oppo A77\r\nDán Cường Lực Oppo A77 chính hãng giá rẻ nhất Hà Nội, TPHCM. Dán cường lực Oppo A77 chịu lực 9H chống xước, vỡ tối đa chỉ có tại MobileCity.\r\n\r\nDán cường lực Oppo A77 là điều hết sức cần thiết để bảo vệ cho \"dế yêu\" bởi màn hình luôn là bộ phận được tương tác nhiều nhất và hay xảy ra hỏng hóc nhất. Nhờ kính cường lực Oppo A77 mà người dùng có thể hạn chế vỡ, xước màn hình và tạo ra lớp bảo vệ tuyệt đối cho \"dế yêu\" khỏi những tác nhân bên ngoài.\r\n\r\nTại sao nên dán cường lực Oppo Oppo A77\r\nKính cường lực Oppo A77 được thiết kế có độ dày 0.26 đến 0.5mm, độ cứng 9H, bền hơn gấp 20 lần so với miếng dán thường. Miếng dán cường lực Oppo A77 cấu tạo bởi những lớp kính kết lại với nhau thành nhiều lớp bên trong như cảm quang, lớp màu sắc, lớp chống vỡ... \r\n\r\nDán cường lực Oppo A77 giúp người dùng sử dụng máy thoải mái hơn, không phải lo lắng mỗi khi xảy ra sự cố. Thiết kế bo tròn ôm sát máy và viền, giúp người dùng không có cảm giác cấn tay khi cầm. Dán cường lực ', 100000, 100000, 50, '107.jpg'),
(109, 2, 4, 'Dán cường lực Oppo F1, F1 Plus', 'Mô tả Dán cường lực Oppo F1, F1 Plus\r\nDán Cường Lực Oppo F1, F1 Plus uy tín, giá rẻ tại Hà Nội, TPHCM. Dán cường lực F1, F1 Plus chịu lực 9H, chống xước, chống vỡ cho điện thoại. \r\n\r\nHiện nay có rất nhiều hãng sản xuất kính cường lực Oppo F1, F1 Plus, nhưng được người dùng tin tưởng và sử dụng nhiều nhất vẫn là Gorilla Glass và Dragontrail. Tấm dán cường lực Oppo F1, F1 Plus giúp người dùng sử dụng thoải mái hơn, tránh va chạm phần màn hình của máy, bảo vệ tốt nhất cho \"gương mặt của dế yêu\"\r\n\r\nCấu tạo của miếng dán cường lực Oppo F1, F1 Plus\r\nKính cường lực Oppo F1, F1 Plus được thiết kế có độ dày 0.26 –  0.3mm, độ cứng 9H, bền hơn tới 20 lần so với miếng dán thường. Phụ kiện này được thiết kế gồm 6 lớp bảo vệ: lớp đầu tiên là lớp đánh bóng, lớp 2 là lớp kính, lớp 3 là lớp khung, lớp 4 là lớp kết hợp (lớp keo), lớp 5 là lớp chống vỡ lớp 6 là lớp dán vào điện thoại. Nhờ thiết kế đó mà tấm dán cường lực Oppo F1, F1 Plus trở nên cứng cáp, bền vững hơn. \r\nDù có đến 6 lớp nhưng kính dán cư', 100000, 100000, 50, '108.jpg'),
(110, 2, 4, 'Dán cường lực Oppo A39 (Neo 9S)', 'Mô tả Dán cường lực Oppo A39 (Neo 9S)\r\nDán cường lực Oppo A39 để bảo vệ màn hình của máy được đảm bảo an toàn nhất. Dán cường lực Oppo Neo 9S tại MobileCity để được nhiều ưu đãi hấp dẫn. Dưới đây là một số chi nhánh của cửa hàng MobileCity tại Hà Nội, TpHCM.\r\n\r\nĐịa chỉ mua tấm dán cường lực Oppo A39 giá rẻ tại Hà Nội, TP.HCM\r\n\r\nHÀ NỘI: Số 120 Thái Hà, Q.Đống Đa - ĐT:  0969.120.120\r\n\r\nCầu Giấy: Số 398 Cầu Giấy, Q.Cầu Giấy - ĐT: 096.1111.398\r\n\r\nTP.HCM: Số 123 Trần Quang Khải, Q.1 - ĐT: 0965.123.123\r\n\r\nCó nên dán cường lực Oppo A39 (Neo 9S) hay không ?\r\nChúng tôi khuyên các bạn nên sử dụng miếng dán cường lực Oppo A39, vì những lợi ích của miếng dán cường lực Oppo Neo 9S mang lại là không thể bàn cãi. Với việc sử dụng miếng dán cường lực cho chiếc Oppo A39 sẽ giúp bảo vệ màn hình Oppo của bạn một cách an toàn nhất. Nếu bạn không sử dụng miếng dán cường lực thì trong trường hợp điện thoại của bạn bị rơi sẽ rất có thể dẫn đến nứt, vỡ hay thậm trí hỏng màn hình. Sẽ rất mất thời gian và tiền ', 100000, 100000, 50, '109.jpg'),
(111, 2, 5, 'Dán cường lực LG G4', 'Mô tả Dán cường lực LG G4\r\nChuyên cung cấp tấm dán màn hình kính cường lực LG G4 tại Hà Nội\r\nMobileCity 120 Thái Hà - Đth: 0969.120120\r\n\r\nCấu tạo màn hình điện thoại hiện nay thông thường gồm 2 lớp: Lớp kính bảo vệ bên ngoài và lớp màn hình hiển thị bên trong. Lớp kính bảo vệ bên ngoài là nơi tiếp xúc với tay và môi trường bên ngoài, nó thường rất hay bị xước. Trong trường hợp điện thoại bị rơi hoặc bị tác động mạnh lớp kính bên ngoài thường bị nứt vỡ. Thay thế mặt kính cảm ứng cho LG G4 thường rất đắt và mất thời gian, chúng ta nên bảo vệ mặt kính trước các va chạm bên ngoài để hạn chế tối đa bị vỡ màn hình, mặt kính.\r\n\r\nTấm dán màn hình cường lực là gì?\r\nCác tấm dán cường lực là một loại kính có cấu tạo từ nhiều lớp. Đây là đặc điểm quan trọng nhất phân biệt tấm dán cường lực với các loại dán bảo vệ màn hình thông thường. Bên cạnh đó, các tấm dán cường lực cũng thường có độ dày lớn hơn (từ 0.2 mm đến 0.4 mm tùy theo từng loại) so với các tấm dán bảo vệ thông thường (chỉ 0.1 mm).', 120000, 120000, 50, '110.jpg'),
(112, 2, 5, 'Dán cường lực LG G7', 'Mô tả Dán cường lực LG G7\r\nDán cường lực LG G7 giá RẺ, chất lượng tốt nhất tại Hà Nội, HCM, Đà Nẵng. Mua dán cường lực LG G7 RẺ, dùng ổn định ngay tại Mobile City.\r\n\r\nDán cường lực LG G7 bảo vệ màn hình điện thoại bạn như thế nào?\r\nVì sao nên dán cường lực LG G7? Bạn đang sở hữu một chiếc LG G7, bạn đang băn khoăn không biết làm gì để có thể bảo vệ màn hình điện thoại của các bạn. Việc này trở nên dễ dàng hơn khi các bạn đến với MobileCity, hãy đến cửa hàng để sở hữu cho mình miếng dán cường lực LG G7 chất lượng nhất và giá thánh lại rẻ hơn so với ngoài thị trường.', 120000, 120000, 50, '111.jpg'),
(113, 2, 5, 'Dán cường lực LG G2 isai L22', 'Mô tả Dán cường lực LG G2 isai L22\r\nDán màn hình kính cường lực LG G2 isai L22 giúp bảo vệ màn hình Smartphone, tablet một cách hoàn hảo với độ cứng lên tới 9H (gấp 20 lần tấm film PET sử dụng trong tấm dán thông thường). Dán màn hình kính cường lực có độ hiển thị hình ảnh với độ nét cao lên tới 99,9% so với hình ảnh hiển thị gốc, có khả năng chống dầu, hạn chế bám vân tay trong quá trình sử dụng. Với chất kết dính silicon mạnh mẽ, dán cường lực LG G2 isai giúp quá trình dán dễ dàng và không ảnh hưởng tới độ nhạy cảm ứng.  Độ dày miếng dán 0.3mm và được xử lý hóa học giúp bảo vệ màn hình tối đa.', 120000, 120000, 50, '112.jpg'),
(114, 2, 5, 'Dán cường lực LG G3 isai', 'Mô tả Dán cường lực LG G3 isai\r\nDán màn hình kính cường lực LG G3 isaigiúp bảo vệ màn hình Smartphone, tablet một cách hoàn hảo với độ cứng lên tới 9H (gấp 20 lần tấm film PET sử dụng trong tấm dán thông thường). Dán màn hình kính cường lực có độ hiển thị hình ảnh với độ nét cao lên tới 99,9% so với hình ảnh hiển thị gốc, có khả năng chống dầu, hạn chế bám vân tay trong quá trình sử dụng. Với chất kết dính silicon mạnh mẽ, Tấm dán kính cường lực LG G G3 isai giúp quá trình dán dễ dàng và không ảnh hưởng tới độ nhạy cảm ứng.  Độ dày miếng dán 0.3mm và được xử lý hóa học giúp bảo vệ màn hình tối đa.', 120000, 120000, 50, '113.jpg'),
(115, 2, 5, 'Dán cường lực LG V30', 'Mô tả Dán cường lực LG V30\r\nDán cường lực LG V30 chính hãng, giá RẺ, Đẹp nhất tại Hà Nội, HCM, Đà Nẵng. Mua miếng dán cường lực LG V30 vừa đẹp vừa RẺ, chính hãng tại Mobile City.\r\n\r\nTác dụng cuả tấm dán cường lực LG V30 là gì?\r\nViệc dán cường lực LG V30 sẽ giúp bảo vệ thiết bị của bạn khỏi những va đập rơi vỡ hay trầy xước do vô tình bị cọ xát màn hình. Đạt chuẩn chịu lực lên tới 12kg/1cm. Và không ảnh hưởng đến chất lượng màu sắc của LG V30.Tấm dán cường lực của LG V30 có độ mỏng tuyệt đối hơn những tấm dán cường lực hiện nay. Được sản xuất từ những chất liệu không độc hại, giúp cho người dùng có thể an tâm dùng sản phẩm này.', 120000, 120000, 50, '114.jpg');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `users`
--

CREATE TABLE `users` (
  `idu` int(11) NOT NULL,
  `fname` varchar(255) NOT NULL,
  `lname` varchar(255) NOT NULL,
  `address` varchar(255) NOT NULL,
  `city` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(15) NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Đang đổ dữ liệu cho bảng `users`
--

INSERT INTO `users` (`idu`, `fname`, `lname`, `address`, `city`, `email`, `password`, `type`) VALUES
(1, 'huyen', 'huyen', 'bac ninh', 'Ha Noi', 'huyen@phoenix.com', 'admin', 'admin');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`idp`);

--
-- Chỉ mục cho bảng `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`idu`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `products`
--
ALTER TABLE `products`
  MODIFY `idp` int(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=116;

--
-- AUTO_INCREMENT cho bảng `users`
--
ALTER TABLE `users`
  MODIFY `idu` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
